### ISSUE TITLE
Auto Decrease Batch Size not working with Self Supervised Training

### ISSUE THREAD

**Issue by Daankrol** [open-edge-platform/training_extensions#2180]
**Describe the bug**

Using both auto decrease batch size and self supervised training results in:
IterBasedRunnerWithCancel: Only one of `max_epochs` or `max_iters` can be set.

**Steps to Reproduce**
see this gist: https://gist.github.com/Daankrol/fa2ca72a29a5a9476310adbd6753e53c
1. Set params.learning_parameters.auto_decrease_batch_size = True
2. Set params.algo_backend.train_type = TrainType.Selfsupervised

**Environment:**

- OS: Linux Ubuntu 18.04
- Framework version: Pytorch 1.13.1
- Python version: 3.8.16
- OpenVINO version: 2022.3.0
- CUDA/cuDNN version: 11.7
- GPU model and memory: NVIDIA GeForce RTX 2080 Ti 12GB

**Comment by eunwoosh** [comment]
I'll check this issue

**Comment by sungmanc** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/2182

**Comment by eunwoosh** [comment]
Because this PR is merged to develop branch, you need to use develop branch if you want to use Auto Decrease Batch Size in Self Supervised Training. And please note that feature name is slightly changed. So if you want to use auto decrease batch size, please use `params.learning_parameters.auto_dapt_batch_size= Safe`.
