### ISSUE TITLE
How to run inference on an exported tiled Object Detection model in C++ (using version/branch 1.6)

### ISSUE THREAD

**Issue by j99ca** [open-edge-platform/training_extensions#3162]
I have an object detection model I trained using the API and using the parameters:

```
hyper_parameters.tiling_parameters.enable_tiling = True
hyper_parameters.learning_parameters.tile_size = 512
```

However I have noticed in the exported IR format model, the model_info parameters from the model.xml file don't seem to match what I would expect:

```
<tile_size value="4096" />
<tiles_overlap value="0.1265021804006746" />
```
I am not sure how that 4096 is populated despite me setting the value to 512 (and the default being 400).

Furthermore, when running inference code at the edge in C++, is there any documentation on how to handle the preprocessing of the input and the merging of the output? The IR model does not seem to handle this on it's own? And the values inside the XML file seems to not indicate what values to use for custom tiling code in C++?

**Comment by eugene123tw** [comment]
@j99ca Please make sure tiling adaptor is switched off (`--tiling_parameters.enable_tiling 0`) otherwise manually configuring won't work. 

@sovrasov Regarding C++, could you share a link for the documentation?

**Comment by eugene123tw** [comment]
We have a sample on how to run OV models in c++ here: https://github.com/openvinotoolkit/model_api?tab=readme-ov-file#c-1, but it doesn't include tiling. That being said, tilers are not difficult to create if a model has already been constructed. Please check the cpp interfaces like https://github.com/openvinotoolkit/model_api/blob/master/model_api/cpp/tilers/include/tilers/detection.h

I'm closing the ticket due to a lack of activity. Please reopen if you have further questions.
